services:
  nginx:
    build:
      context: .
    container_name: nginx-certbot
    restart: always
    ports:
      - "80:80"
    volumes:
      - certbot-data:/etc/letsencrypt

volumes:
  certbot-data:
